language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: SUSGIOBUI1RZJT1Bb+00ARVZJpn6RxXZxhzDWS8psKJoG+1KJ4/0fJXSjt92Lrj3pHEvzjXCLL8KidBsbzBoJg5acAQ7dnvPJZart/Tv5pumcHXu6+hfrcR5SlTLKqVz2+akplXeKOJzhiN+GvOekVZe4LBC3oWynRnstfHvcNM=
  on:
    tags: true
    all_branches: true
