language: node_js
node_js:
- 5.6
sudo: false
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: OK4cOF029sUiA6wh0540aHCLjBtufC2fBam52FD9z7AMfl2ygDO+OeMDNf+vyMy/ByS7HMJwbJpYjaWwM9gk5tD7TQfbgeOjuCMfyzDyMHyVa70/CXQqHZGbVPC6AzGsi26l0yyH562hxkSORmJ6kdvf/X5DFlvoUOFDT1/KK/Y=
  on:
    tags: true
    all_branches: true
